spring:
  application:
    name: transactions
  datasource:
    url: jdbc:postgresql://postgres:5432/bank
    username: postgres
    password: bankpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  -Duser.timezone: Asia/Kolkata
  docker:
    compose:
      enabled: false
  jackson:
    time-zone: Asia/Kolkata
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
